require("nvim-treesitter").setup({
  highlight = { enable = true },
  indent = { enable = true },
  ensure_installed = {
    "bash",
    "c",
    "go",
    "gomod",
    "gowork",
    "haskell",
    "hcl",
    "html",
    "json",
    "markdown",
    "markdown_inline",
    "python",
    "ruby",
    "rust",
    "scala",
    "tsx",
    "typescript",
    "xml",
    "yaml",
  },
})
