-- Belafonte Day — the light half of the Ghostty theme pair configured in
-- ~/.config/ghostty/config (`theme = light:Belafonte Day,dark:Melange Dark`).
-- Highlight groups are generated by mini.base16 from the palette below.
--
-- Background, foreground, selection, and the ANSI red are taken verbatim from
-- Ghostty's "Belafonte Day" theme. The remaining accents are Belafonte's own
-- hues darkened to 4:1 contrast against the background — at their terminal
-- lightness, yellow (1.8:1), cyan (1.8:1), and green (2.5:1) are unreadable as
-- syntax colors on parchment. The neutral ramp steps Belafonte doesn't define
-- (base01, base03, base04, base06) are interpolated between the ones it does.
require("mini.base16").setup({
  palette = {
    base00 = "#d5ccba", -- background (Ghostty `background`)
    base01 = "#c5bcac", -- cursorline, statusline
    base02 = "#968c83", -- visual selection (Ghostty `selection-background`)
    base03 = "#766b67", -- comments
    base04 = "#524447", -- dim foreground
    base05 = "#45373c", -- foreground (Ghostty `foreground`)
    base06 = "#32242c",
    base07 = "#20111b", -- ANSI black
    base08 = "#be100e", -- red: variables, errors
    base09 = "#8f4e2a", -- orange: numbers, constants
    base0A = "#81561d", -- yellow: types, search
    base0B = "#626049", -- green: strings
    base0C = "#5e5f61", -- cyan: escapes, info
    base0D = "#3f6473", -- blue: functions
    base0E = "#8f4e2a", -- magenta: keywords (Belafonte has no distinct violet)
    base0F = "#5e5252",
  },
})

vim.g.colors_name = "belafonte-day"
