-- Blue Dolphin — the day half of the "blue" theme pair (night is hivacruz).
-- Ported from Ghostty's "Blue Dolphin" terminal theme. Both halves of this pair are
-- dark-background themes; "day" names the pair member, not the luminance.
-- Highlight groups are generated by mini.base16 from the palette below.
--
-- Background and foreground are taken verbatim from Ghostty. Blue Dolphin's
-- background (#006984) is a mid-luminance teal, so contrast against it is capped at
-- 6.26:1 (pure white) — the same squeeze Fairyfloss has. Accents therefore keep
-- their Ghostty hue and are lifted only as far as their floor: 4.5:1 for the
-- high-traffic slots (base03/0B/0D/0F), 3:1 for the rest. The result is pastel by
-- construction; that is Blue Dolphin.
--
--   base03  #9094a4 -> #d9dbe0  (2.07 -> 4.52)
--   base08  #ff8288 -> #ff969b  (2.62 -> 3.01)
--   base0B  #b4e88d -> #b8e993  (4.43 -> 4.51)
--   base0D  #82aaff -> #cbdcff  (2.73 -> 4.54)
--   base0F  #ddb0f6 -> #ecd2fa  (3.46 -> 4.52)
--
-- The neutral ramp runs *darker* than base00 rather than lighter: base00 is already
-- mid-luminance, and Ghostty's `selection-background` (#2baeca) leaves selected text
-- at 2.19:1 because mini.base16 keeps base05 as the Visual foreground. base02 is a
-- darkened teal instead (base05 on base02 = 9.33).
require("mini.base16").setup({
  palette = {
    base00 = "#006984", -- background (Ghostty `background`)
    base01 = "#00566c", -- cursorline, statusline
    base02 = "#004152", -- visual selection (darkened; see header)
    base03 = "#d9dbe0", -- comments, line numbers, sign column
    base04 = "#cfe6f0", -- dim foreground
    base05 = "#c5f2ff", -- foreground (Ghostty `foreground`)
    base06 = "#e2f8ff",
    base07 = "#ffffff",
    base08 = "#ff969b", -- red: variables, errors
    base09 = "#f4d69f", -- sand: numbers, constants
    base0A = "#ffe585", -- yellow: types, search
    base0B = "#b8e993", -- green: strings
    base0C = "#89ebff", -- cyan: escapes, info
    base0D = "#cbdcff", -- blue: functions
    base0E = "#e9c1ff", -- violet: keywords
    base0F = "#ecd2fa", -- pale violet: delimiters
  },
})

vim.g.colors_name = "blue-dolphin"
