-- Chalk — the day half of the "black" theme pair (night is gruvbox-dark-hard).
-- Ported from Ghostty's "Chalk" terminal theme. Both halves of this pair are
-- dark-background themes; "day" names the pair member, not the luminance.
-- Highlight groups are generated by mini.base16 from the palette below.
--
-- Background, foreground, and six of the eight accents are taken verbatim from
-- Ghostty. Chalk's `selection-background` is #e4e8ed, a near-white meant to pair
-- with its own `selection-foreground`; mini.base16 keeps base05 as the Visual
-- foreground, so that value is unusable as base02 and the selection is taken from
-- the neutral ramp instead (base05 on base02 = 5.91). #e4e8ed is reused as base06.
--
--   base03  #888888 -> #939393  (3.90 -> 4.50)
--   base0F  #bd4f5a -> #ce7c84  (2.92 -> 4.51)
--   base09  synthesized from ANSI red and yellow; Chalk has no orange
require("mini.base16").setup({
  palette = {
    base00 = "#2b2d2e", -- background (Ghostty `background`)
    base01 = "#3e3f40", -- cursorline, statusline
    base02 = "#4d4f4f", -- visual selection (interpolated; see header)
    base03 = "#939393", -- comments, line numbers, sign column
    base04 = "#b9bcbd", -- dim foreground
    base05 = "#d2d8d9", -- foreground (Ghostty `foreground`)
    base06 = "#e4e8ed", -- Ghostty `selection-background`, used as a light neutral
    base07 = "#ffffff",
    base08 = "#f24840", -- red: variables, errors
    base09 = "#f89751", -- orange: numbers, constants (synthesized)
    base0A = "#ffeb62", -- yellow: types, search
    base0B = "#80c470", -- green: strings
    base0C = "#53cdbd", -- cyan: escapes, info
    base0D = "#4196ff", -- blue: functions
    base0E = "#fc5275", -- pink: keywords
    base0F = "#ce7c84", -- rose: delimiters
  },
})

vim.g.colors_name = "chalk"
