-- Django Smooth — the day half of the "emerald" theme pair (night is
-- django-reborn-again). Ported from Ghostty's "Django Smooth" terminal theme, which
-- is Django's palette over a lighter, softer green. Both halves of this pair are
-- dark-background themes; "day" names the pair member, not the luminance.
-- Highlight groups are generated by mini.base16 from the palette below.
--
-- Background, foreground, and the visual selection are taken verbatim from Ghostty,
-- as are five of the eight accents. Django Smooth inherits Django's two degenerate
-- ANSI slots: its blue is the neutral grey #989898, which collides with base03's
-- role, and its magenta is plain #f8f8f8, the same white as the foreground.
--
--   base03  #989898 -> #b5b5b5  (3.21 -> 4.51)
--   base0B  #41a83e -> #6ec96b  (3.04 -> 4.51)
--   base0D  #989898 -> #5fd9a0  substituted; ANSI blue is a neutral grey
--   base0E  #f8f8f8 -> #ff943b  substituted; ANSI magenta duplicates the foreground
--   base0F  sage grey carried over from django-reborn-again, lifted to 4.50
require("mini.base16").setup({
  palette = {
    base00 = "#245032", -- background (Ghostty `background`)
    base01 = "#2c5b3b", -- cursorline, statusline
    base02 = "#336442", -- visual selection (Ghostty `selection-background`)
    base03 = "#b5b5b5", -- comments, line numbers, sign column
    base04 = "#dadada", -- dim foreground
    base05 = "#f8f8f8", -- foreground (Ghostty `foreground`)
    base06 = "#fcfcfc",
    base07 = "#ffffff",
    base08 = "#fd6209", -- red: variables, errors
    base09 = "#ffff94", -- pale yellow: numbers, constants
    base0A = "#ffe862", -- yellow: types, search
    base0B = "#6ec96b", -- green: strings
    base0C = "#9df39f", -- light green: escapes, info
    base0D = "#5fd9a0", -- mint: functions
    base0E = "#ff943b", -- orange: keywords
    base0F = "#9bbda5", -- sage grey: delimiters
  },
})

vim.g.colors_name = "django-smooth"
