-- Django Reborn Again — the night half of the "emerald" theme pair (day is django).
-- Ported from Ghostty's "Django Reborn Again" terminal theme. It shares Django's
-- ANSI accents and differs in its darker background, softer foreground, and its own
-- neutral ramp. Highlight groups are generated by mini.base16 from the palette below.
--
-- Background, foreground, and the visual selection are taken verbatim from
-- Ghostty, as are six of the eight accents. Same two degeneracies as django.lua:
-- the ANSI blue is a near-black green and the ANSI magenta duplicates #f8f8f8.
--
--   base03  #4c4c4c -> #828282  (2.02 -> 4.51)
--   base0D  #245032 -> #41925b  (1.87 -> 4.53)
--   base0F  #568264 -> #5d8d6c  (3.94 -> 4.53)
--   base0E  #f8f8f8 -> #ff943b  substituted; ANSI magenta duplicates the foreground
--
-- Ghostty's `cursor-color` for this theme is #ffcc00; mini.base16 derives the
-- cursor from the palette, so that gold is not represented here.
require("mini.base16").setup({
  palette = {
    base00 = "#051f14", -- background (Ghostty `background`)
    base01 = "#122b1e", -- cursorline, statusline
    base02 = "#203727", -- visual selection (Ghostty `selection-background`)
    base03 = "#828282", -- comments, line numbers, sign column
    base04 = "#aeb0af", -- dim foreground
    base05 = "#dadedc", -- foreground (Ghostty `foreground`)
    base06 = "#eceeee",
    base07 = "#ffffff",
    base08 = "#fd6209", -- red: variables, errors
    base09 = "#ffff94", -- pale yellow: numbers, constants
    base0A = "#ffe862", -- yellow: types, search
    base0B = "#41a83e", -- green: strings
    base0C = "#9df39f", -- light green: escapes, info
    base0D = "#41925b", -- sage: functions
    base0E = "#ff943b", -- orange: keywords
    base0F = "#5d8d6c", -- sage grey: delimiters
  },
})

vim.g.colors_name = "django-reborn-again"
