-- Django — the day half of the "emerald" theme pair (night is django-reborn-again).
-- Ported from Ghostty's "Django" terminal theme. Both halves of this pair are
-- dark-background themes; "day" names the pair member, not the luminance.
-- Highlight groups are generated by mini.base16 from the palette below.
--
-- Background, foreground, and the visual selection are taken verbatim from
-- Ghostty, as are six of the eight accents. Django's ANSI palette is degenerate in
-- two places: its blue is a near-black green (1.92:1, unreadable as a function
-- colour) and its magenta is plain #f8f8f8, the same white as the foreground.
-- The blue slots are lifted to the 4.5:1 floor keeping their hue; the magenta slot
-- borrows ANSI bright red so keywords stay distinct from every green in the theme.
--
--   base03  #585858 -> #8f8f8f  (2.05 -> 4.50)
--   base0D  #315d3f -> #549f6b  (1.92 -> 4.54)
--   base0F  #568264 -> #679b77  (3.31 -> 4.53)
--   base0E  #f8f8f8 -> #ff943b  substituted; ANSI magenta duplicates the foreground
require("mini.base16").setup({
  palette = {
    base00 = "#0b2f20", -- background (Ghostty `background`)
    base01 = "#184029", -- cursorline, statusline
    base02 = "#245032", -- visual selection (Ghostty `selection-background`)
    base03 = "#8f8f8f", -- comments, line numbers, sign column
    base04 = "#c4c4c4", -- dim foreground
    base05 = "#f8f8f8", -- foreground (Ghostty `foreground`)
    base06 = "#fcfcfc",
    base07 = "#ffffff",
    base08 = "#fd6209", -- red: variables, errors
    base09 = "#ffff94", -- pale yellow: numbers, constants
    base0A = "#ffe862", -- yellow: types, search
    base0B = "#41a83e", -- green: strings
    base0C = "#9df39f", -- light green: escapes, info
    base0D = "#549f6b", -- sage: functions
    base0E = "#ff943b", -- orange: keywords
    base0F = "#679b77", -- sage grey: delimiters
  },
})

vim.g.colors_name = "django"
