-- Fairyfloss — the day half of the "cyber" theme pair (night is tokyonight-moon).
-- Ported from Ghostty's "Fairyfloss" terminal theme. Despite sitting in the day
-- slot it is a dark-background theme; the pair member, not the luminance, is what
-- "day" names here. Highlight groups are generated by mini.base16 from the palette
-- below.
--
-- Background, foreground, and the visual selection are taken verbatim from
-- Ghostty. Its parchment-purple background caps contrast at 7.10:1 against pure
-- white, so a flat 4.5:1 floor would wash the whole palette to pastel and collapse
-- ANSI red onto ANSI magenta. Instead the floor is split by how much text a slot
-- actually paints: 4.5:1 for the high-traffic roles (base03 comments/line numbers,
-- base0B strings, base0D functions, base0F delimiters) and 3:1 for the accents.
-- Only three values needed lifting; the rest are Fairyfloss's own syntax colors.
--
--   base03  #8077a8 -> #cfccde  (1.73 -> 4.51)  selection hue, reused as the dim neutral
--   base08  #f92672 -> #fc81ad  (1.87 -> 3.00)
--   base0F  #6090cb -> #bcd0e9  (2.15 -> 4.51)
--   Comment #e6c000 -> #f3cb00  (4.02 -> 4.51)  see the override below
require("mini.base16").setup({
  palette = {
    base00 = "#5a5475", -- background (Ghostty `background`)
    base01 = "#6d668e", -- cursorline, statusline
    base02 = "#8077a8", -- visual selection (Ghostty `selection-background`)
    base03 = "#cfccde", -- comments, line numbers, sign column
    base04 = "#e4e2e8", -- dim foreground
    base05 = "#f8f8f2", -- foreground (Ghostty `foreground`)
    base06 = "#fcfcf8",
    base07 = "#ffffff",
    base08 = "#fc81ad", -- red: variables, errors
    base09 = "#c5a3ff", -- violet: numbers, constants
    base0A = "#c2ffdf", -- mint: types, search
    base0B = "#ffea00", -- yellow: strings
    base0C = "#ff857f", -- salmon: escapes, info
    base0D = "#fff352", -- bright yellow: functions
    base0E = "#ffb8d1", -- pink: keywords
    base0F = "#bcd0e9", -- blue: delimiters
  },
})

-- Gold comments are Fairyfloss's signature, but base03 also drives LineNr,
-- SignColumn, StatusLineNC, and TabLine — gold there would be unreadable noise.
-- So base03 stays a neutral and Comment alone gets the gold back.
vim.api.nvim_set_hl(0, "Comment", { fg = "#f3cb00" })

vim.g.colors_name = "fairyfloss"
