-- Gruvbox Dark Hard — the night half of the "black" theme pair (day is chalk).
-- Ported from Ghostty's "Gruvbox Dark Hard" terminal theme. Highlight groups are
-- generated by mini.base16 from the palette below.
--
-- Background, foreground, the visual selection, and seven of the eight accents are
-- taken verbatim from Ghostty. Gruvbox's own base16 scheme puts #665c54 in base03,
-- which reads at 2.02:1 here; this port uses the theme's own fg4 (ANSI 7) instead,
-- so comments clear the 4.5:1 floor without inventing a colour.
--
--   base03  #665c54 -> #a89984  (2.02 -> 5.90, ANSI 7)
--   base0F  #d65d0e -> #de600f  (4.24 -> 4.52)
--   base09  #fe8019  gruvbox's canonical orange; Ghostty's 16 slots have none
require("mini.base16").setup({
  palette = {
    base00 = "#1d2021", -- background (Ghostty `background`)
    base01 = "#3c3836", -- cursorline, statusline
    base02 = "#665c54", -- visual selection (Ghostty `selection-background`)
    base03 = "#a89984", -- comments, line numbers, sign column
    base04 = "#bdae93", -- dim foreground
    base05 = "#ebdbb2", -- foreground (Ghostty `foreground`)
    base06 = "#f2e5bc",
    base07 = "#fbf1c7",
    base08 = "#fb4934", -- red: variables, errors
    base09 = "#fe8019", -- orange: numbers, constants
    base0A = "#fabd2f", -- yellow: types, search
    base0B = "#b8bb26", -- green: strings
    base0C = "#8ec07c", -- aqua: escapes, info
    base0D = "#83a598", -- blue: functions
    base0E = "#d3869b", -- purple: keywords
    base0F = "#de600f", -- dark orange: delimiters
  },
})

vim.g.colors_name = "gruvbox-dark-hard"
