-- Hivacruz — the night half of the "blue" theme pair (day is blue-dolphin).
-- Ported from Ghostty's "Hivacruz" terminal theme, an Atelier Sulphurpool palette
-- over a darker navy background. Highlight groups are generated by mini.base16 from
-- the palette below.
--
-- Background, foreground, the visual selection, and six of the eight accents are
-- taken verbatim from Ghostty. Ghostty's ANSI 11 and 12 are both greys rather than
-- a bright yellow and blue, so base03 takes ANSI 12 (#898ea4, 4.75:1) as its neutral
-- and the accent slots come from the normal-intensity half of the palette.
--
--   base0D  #3d8fd1 -> #3f90d2  (4.44 -> 4.50)
--   base0F  #9c637a -> #ad7e91  (3.29 -> 4.53)
require("mini.base16").setup({
  palette = {
    base00 = "#132638", -- background (Ghostty `background`)
    base01 = "#243449", -- cursorline, statusline
    base02 = "#5e6687", -- visual selection (Ghostty `selection-background`)
    base03 = "#898ea4", -- comments, line numbers, sign column
    base04 = "#c0bdc7", -- dim foreground
    base05 = "#ede4e4", -- foreground (Ghostty `foreground`)
    base06 = "#f5f7ff", -- ANSI bright white
    base07 = "#ffffff",
    base08 = "#c94922", -- red: variables, errors
    base09 = "#c76b29", -- orange: numbers, constants
    base0A = "#c08b30", -- yellow: types, search
    base0B = "#73ad43", -- green: strings
    base0C = "#22a2c9", -- cyan: escapes, info
    base0D = "#3f90d2", -- blue: functions
    base0E = "#6679cc", -- indigo: keywords
    base0F = "#ad7e91", -- rose: delimiters
  },
})

vim.g.colors_name = "hivacruz"
