name: CI

on:
  push:
    branches: ["**"]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:/repo" \
            -w /repo \
            nixos/nix \
            sh -c "git config --global --add safe.directory /repo && nix develop --extra-experimental-features 'nix-command flakes' --command sh -c 'stylua --check . && nixfmt --check flake.nix modules/*.nix'"

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:/repo" \
            -w /repo \
            nixos/nix \
            sh -c "git config --global --add safe.directory /repo && nix develop --extra-experimental-features 'nix-command flakes' --command sh -c 'luacheck lua/'"
