name: CI

on:
  push:
    branches: ["**"]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v14
      - name: Lint
        run: nix develop --command sh -c "stylua --check . && nixfmt --check flake.nix modules/*.nix"

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v14
      - name: Test
        run: nix develop --command sh -c "luacheck lua/ && nvim --headless -u lua/init.lua +qa"
